Fix: wpml default directory changing home url
themeum/tutor pull request #1448
Opened 2024-12-06 07:59 UTC by Anindra123

2024-12-06 08:59 UTC, harunollyo requested changes

2024-12-06 08:59 UTC, harunollyo commented on views/quiz/attempt-table.php
> +										$admin_url = add_query_arg(
```php
$url_args   = array( 'view_quiz_attempt_id' => $attempt->attempt_id );
$front_url  = add_query_arg( $url_args, tutor()->current_url );
$admin_url  = add_query_arg( $url_args, admin_url( 'admin.php?page=tutor_quiz_attempts' ) );
```

2024-12-06 08:59 UTC, harunollyo commented on views/qna/qna-table.php
> +										<?php
```php
$url_args   = array( 'view_quiz_attempt_id' => $attempt->attempt_id );
$front_url  = add_query_arg( $url_args, tutor()->current_url );
$admin_url  = add_query_arg( $url_args, admin_url( 'admin.php?page=question_answer' ) );
```

2024-12-06 09:43 UTC, harunollyo requested changes

2024-12-06 09:43 UTC, harunollyo commented on classes/Assets.php
>  			'home_url'                     => get_home_url(),
```php
rtrim( get_home_url(), '/')
```

2024-12-09 07:27 UTC, sazedul-haque requested changes

2024-12-09 07:27 UTC, sazedul-haque commented on assets/react/v3/shared/atoms/WPEditor.tsx
> +        `${tutorConfig.asset_base_url}/wp-includes/css/dashicons.min.css,${tutorConfig.asset_base_url}/wp-includes/js/tinymce/skins/wordpress/wp-content.css,${tutorConfig.asset_base_url}/wp-content/p
Use `site_url` here as we are reffering the wp-includes directory.

2024-12-09 09:55 UTC, sazedul-haque approved these changes

2024-12-09 09:58 UTC, merged