New settings added for instructors
themeum/tutor pull request #1483
Opened 2024-12-24 04:25 UTC by sazedul-haque

2024-12-24 04:27 UTC, b-l-i-n-d approved these changes

2025-01-02 04:42 UTC, harunollyo requested changes

2025-01-02 04:42 UTC, harunollyo commented on classes/Course.php
> +			$this->json_response( $is_error->get_error_message(), null, HttpHelper::STATUS_INTERNAL_SERVER_ERROR );
Use bad request instead of internal error.
```php
$this->response_bad_request( $is_error->get_error_message() );
```

2025-01-02 06:05 UTC, harunollyo approved these changes

2025-01-02 06:05 UTC, merged