🎉 Session helper class added with PHPUnit test case
themeum/tutor pull request #369
Opened 2023-03-13 12:00 UTC by harunollyo

PHPUnit test result
<img width="288" alt="session-unit-test" src="https://user-images.githubusercontent.com/97671808/224679868-27cdc5b2-575f-406a-9b3d-7022a7db99cc.png">

Run the test case by the following command
`vendor/bin/phpunit --filter=SessionHelperTest`

To avoid PHPUnit error, use this at the beginning of `tutor/tests/bootstrap.php` file
```php
! session_id() ? session_start() : 0;
```

2023-03-14 05:29 UTC, shewa12 requested changes

2023-03-14 06:47 UTC, harunollyo commented on helpers/SessionHelper.php
> +		session_destroy();
It's not used in the current code anywhere, if anytime we need it, we can use it from here.

2023-03-14 06:47 UTC, harunollyo commented on helpers/SessionHelper.php
> +		session_unset();
It's not used in the current code anywhere, if anytime we need it, we can use it from here.

2023-03-17 05:24 UTC, shewa12 approved these changes

2023-03-17 05:25 UTC, merged