instructor reject action for email issue
themeum/tutor pull request #599
Opened 2023-11-01 04:49 UTC by ibrahim-kardi

instructor rejection new action added, and email not  sending instructor rejection issue fixed

2023-11-01 06:31 UTC, harunollyo requested changes

2023-11-01 06:31 UTC, harunollyo commented on views/pages/instructors.php
>  	$instructor_status = array( 'pending' );
Simply add it like as below
```php
$instructor-action['reject'] = array( __( 'Reject', 'tutor' ), 'select-danger' );
```

2023-11-01 06:31 UTC, harunollyo commented on classes/Instructors_List.php
> +			do_action( 'tutor_after_rejected_instructor', $instructor_id );
action trigger should not be outside of the loop.

2023-11-01 06:31 UTC, harunollyo commented on classes/Instructors_List.php
> +				self::remove_instructor_role( $instructor_id, $status );
Remove the hooks from this method and make action specific method by wrapping this method.

2023-11-01 07:16 UTC, ibrahim-kardi commented on views/pages/instructors.php
>  	$instructor_status = array( 'pending' );
updated @harunollyo vai

2023-11-02 04:28 UTC, harunollyo requested changes

2023-11-02 04:28 UTC, harunollyo commented on classes/Instructors_List.php
> +				self::instructor_blockage( $instructor_id, $status );
Remove the status param and pass the param statically from `instructor_blockage` method.

2023-11-06 09:47 UTC, harunollyo approved these changes

2023-11-06 09:48 UTC, merged