[FE] Create the course basic step.
themeum/tutor pull request #667
Opened 2024-02-05 07:44 UTC by sazedul-haque

2024-02-12 12:00 UTC, ahamed requested changes

2024-02-12 12:08 UTC, ahamed requested changes

2024-02-12 12:08 UTC, ahamed commented on assets/react/v3/entries/course-builder/components/layouts/Layout.tsx
> +    action: 'tutor_course_details',
Move this action to the `useCourseDetailsQuery` implementation.

2024-02-12 12:08 UTC, ahamed commented on assets/react/v3/entries/course-builder/services/course.ts
> +    queryKey: [payload.course_id],
Use a query key name
`queryKey: ['CourseDetails', payload.course_id]`

2024-02-13 04:40 UTC, sazedul-haque commented
@ahamed Vai, all the recommended changes are committed.

2024-02-13 10:14 UTC, ahamed approved these changes

2024-02-13 11:09 UTC, merged