[FE] Create Add Lesson Modal
themeum/tutor pull request #697
Opened 2024-02-23 08:48 UTC by b-l-i-n-d

2024-02-23 10:31 UTC, ahamed requested changes

2024-02-23 10:31 UTC, ahamed commented on assets/react/v3/shared/components/modals/AddLessonModal.tsx
> +                  placeholder={__('Enter Lesson name', 'tutor')}
```suggestion
                  placeholder={__('Enter Lesson Name', 'tutor')}
```

2024-02-23 10:31 UTC, ahamed commented on assets/react/v3/shared/components/modals/AddLessonModal.tsx
> +                  placeholder={__('Enter Lesson name', 'tutor')}
```suggestion
                  placeholder={__('Enter Lesson Description', 'tutor')}
```

2024-02-23 10:31 UTC, ahamed commented on assets/react/v3/shared/components/modals/AddLessonModal.tsx
> +    padding-right: ${spacing[64]};
```suggestion
    padding-inline: ${spacing[24]} ${spacing[64]};
```

2024-02-23 10:31 UTC, ahamed commented on assets/react/v3/shared/components/modals/AddLessonModal.tsx
> +    row-gap: ${spacing[24]};
```suggestion
    gap: ${spacing[24]};
```

2024-02-23 10:31 UTC, ahamed commented on assets/react/v3/shared/components/modals/AddLessonModal.tsx
> +    row-gap: ${spacing[16]};
Do we really need `row-gap`?
```suggestion
    gap: ${spacing[16]};
```

2024-02-23 10:31 UTC, ahamed commented on assets/react/v3/shared/components/modals/AddLessonModal.tsx
> +    padding-left: ${spacing[64]};
```suggestion
    padding-inline: ${spacing[64]} ${spacing[24]};
```

2024-02-23 10:31 UTC, ahamed commented on assets/react/v3/shared/components/modals/AddLessonModal.tsx
> +    column-gap: ${spacing[8]};
```suggestion
    gap: ${spacing[8]};
```

2024-02-23 10:31 UTC, ahamed commented on assets/react/v3/shared/components/modals/AddLessonModal.tsx
> +    row-gap: ${spacing[8]};
```suggestion
    gap: ${spacing[8]};
```

2024-02-23 10:31 UTC, ahamed commented on assets/react/v3/shared/components/modals/ModalWrapper.tsx
> +  onClose?: () => void;
Why do you make this optional?

2024-02-23 10:31 UTC, ahamed commented on assets/react/v3/shared/components/modals/ModalWrapper.tsx
> +    max-height: 72px;
Use `height` instead.

2024-02-23 10:31 UTC, ahamed commented on assets/react/v3/shared/components/modals/ModalWrapper.tsx
> +        border: 0.5px solid ${colorTokens.icon.hints};
Fraction px value may not work all the browsers well. Use nearest integer value.

2024-02-23 10:31 UTC, ahamed commented on assets/react/v3/shared/config/icon-list.ts
> +    viewBox: '0 0 24 24',
Better use `fill="currentColor"` for modifying the SVG colors.

2024-02-23 10:50 UTC, b-l-i-n-d commented on assets/react/v3/shared/components/modals/ModalWrapper.tsx
> +  onClose?: () => void;
Bhai this was a mistake.

2024-02-27 05:12 UTC, ahamed approved these changes

2024-02-28 11:16 UTC, merged